# Generated by Django 4.2.7 on 2026-02-19 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('log_entries', models.JSONField(help_text='Array of {status, start_time, end_time, duration, notes}')),
                ('total_driving_hours', models.FloatField()),
                ('total_on_duty_hours', models.FloatField()),
                ('total_off_duty_hours', models.FloatField()),
                ('remaining_drive_time', models.FloatField()),
                ('remaining_on_duty_time', models.FloatField()),
                ('cycle_hours_remaining', models.FloatField()),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_location', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('current_cycle_used', models.FloatField(help_text='Hours used out of 70 in rolling 8 days')),
                ('total_miles', models.FloatField(blank=True, null=True)),
                ('total_driving_hours', models.FloatField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('route_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hos_app.dailylog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='hos_app.trip'),
        ),
    ]
